spring:
  h2:
    console:
      enabled: true
      path: /db-ui
  datasource:
    url: jdbc:h2:mem:grpc-client-java
    username: sa
    password: grpc
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update