// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cpf.proto

package com.lucasilva.grpc.integration.grpc;

public final class Cpf {
  private Cpf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CpfRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:serasa.CpfRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string cpf = 1;</code>
     */
    java.lang.String getCpf();
    /**
     * <code>string cpf = 1;</code>
     */
    com.google.protobuf.ByteString
        getCpfBytes();
  }
  /**
   * Protobuf type {@code serasa.CpfRequest}
   */
  public  static final class CpfRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:serasa.CpfRequest)
      CpfRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CpfRequest.newBuilder() to construct.
    private CpfRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CpfRequest() {
      cpf_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CpfRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              cpf_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lucasilva.grpc.integration.grpc.Cpf.internal_static_serasa_CpfRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lucasilva.grpc.integration.grpc.Cpf.internal_static_serasa_CpfRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest.class, com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest.Builder.class);
    }

    public static final int CPF_FIELD_NUMBER = 1;
    private volatile java.lang.Object cpf_;
    /**
     * <code>string cpf = 1;</code>
     */
    public java.lang.String getCpf() {
      java.lang.Object ref = cpf_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cpf_ = s;
        return s;
      }
    }
    /**
     * <code>string cpf = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCpfBytes() {
      java.lang.Object ref = cpf_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cpf_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCpfBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cpf_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCpfBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cpf_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest)) {
        return super.equals(obj);
      }
      com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest other = (com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest) obj;

      boolean result = true;
      result = result && getCpf()
          .equals(other.getCpf());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CPF_FIELD_NUMBER;
      hash = (53 * hash) + getCpf().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code serasa.CpfRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:serasa.CpfRequest)
        com.lucasilva.grpc.integration.grpc.Cpf.CpfRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lucasilva.grpc.integration.grpc.Cpf.internal_static_serasa_CpfRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lucasilva.grpc.integration.grpc.Cpf.internal_static_serasa_CpfRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest.class, com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest.Builder.class);
      }

      // Construct using com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        cpf_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lucasilva.grpc.integration.grpc.Cpf.internal_static_serasa_CpfRequest_descriptor;
      }

      @java.lang.Override
      public com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest getDefaultInstanceForType() {
        return com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest build() {
        com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest buildPartial() {
        com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest result = new com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest(this);
        result.cpf_ = cpf_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest) {
          return mergeFrom((com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest other) {
        if (other == com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest.getDefaultInstance()) return this;
        if (!other.getCpf().isEmpty()) {
          cpf_ = other.cpf_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object cpf_ = "";
      /**
       * <code>string cpf = 1;</code>
       */
      public java.lang.String getCpf() {
        java.lang.Object ref = cpf_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cpf_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cpf = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCpfBytes() {
        java.lang.Object ref = cpf_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cpf_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cpf = 1;</code>
       */
      public Builder setCpf(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cpf_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cpf = 1;</code>
       */
      public Builder clearCpf() {
        
        cpf_ = getDefaultInstance().getCpf();
        onChanged();
        return this;
      }
      /**
       * <code>string cpf = 1;</code>
       */
      public Builder setCpfBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cpf_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:serasa.CpfRequest)
    }

    // @@protoc_insertion_point(class_scope:serasa.CpfRequest)
    private static final com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest();
    }

    public static com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CpfRequest>
        PARSER = new com.google.protobuf.AbstractParser<CpfRequest>() {
      @java.lang.Override
      public CpfRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CpfRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CpfRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CpfRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lucasilva.grpc.integration.grpc.Cpf.CpfRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CpfResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:serasa.CpfResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string situacao = 1;</code>
     */
    java.lang.String getSituacao();
    /**
     * <code>string situacao = 1;</code>
     */
    com.google.protobuf.ByteString
        getSituacaoBytes();
  }
  /**
   * Protobuf type {@code serasa.CpfResponse}
   */
  public  static final class CpfResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:serasa.CpfResponse)
      CpfResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CpfResponse.newBuilder() to construct.
    private CpfResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CpfResponse() {
      situacao_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CpfResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              situacao_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lucasilva.grpc.integration.grpc.Cpf.internal_static_serasa_CpfResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lucasilva.grpc.integration.grpc.Cpf.internal_static_serasa_CpfResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse.class, com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse.Builder.class);
    }

    public static final int SITUACAO_FIELD_NUMBER = 1;
    private volatile java.lang.Object situacao_;
    /**
     * <code>string situacao = 1;</code>
     */
    public java.lang.String getSituacao() {
      java.lang.Object ref = situacao_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        situacao_ = s;
        return s;
      }
    }
    /**
     * <code>string situacao = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSituacaoBytes() {
      java.lang.Object ref = situacao_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        situacao_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSituacaoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, situacao_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSituacaoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, situacao_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse)) {
        return super.equals(obj);
      }
      com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse other = (com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse) obj;

      boolean result = true;
      result = result && getSituacao()
          .equals(other.getSituacao());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SITUACAO_FIELD_NUMBER;
      hash = (53 * hash) + getSituacao().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code serasa.CpfResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:serasa.CpfResponse)
        com.lucasilva.grpc.integration.grpc.Cpf.CpfResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lucasilva.grpc.integration.grpc.Cpf.internal_static_serasa_CpfResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lucasilva.grpc.integration.grpc.Cpf.internal_static_serasa_CpfResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse.class, com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse.Builder.class);
      }

      // Construct using com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        situacao_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lucasilva.grpc.integration.grpc.Cpf.internal_static_serasa_CpfResponse_descriptor;
      }

      @java.lang.Override
      public com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse getDefaultInstanceForType() {
        return com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse build() {
        com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse buildPartial() {
        com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse result = new com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse(this);
        result.situacao_ = situacao_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse) {
          return mergeFrom((com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse other) {
        if (other == com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse.getDefaultInstance()) return this;
        if (!other.getSituacao().isEmpty()) {
          situacao_ = other.situacao_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object situacao_ = "";
      /**
       * <code>string situacao = 1;</code>
       */
      public java.lang.String getSituacao() {
        java.lang.Object ref = situacao_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          situacao_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string situacao = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSituacaoBytes() {
        java.lang.Object ref = situacao_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          situacao_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string situacao = 1;</code>
       */
      public Builder setSituacao(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        situacao_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string situacao = 1;</code>
       */
      public Builder clearSituacao() {
        
        situacao_ = getDefaultInstance().getSituacao();
        onChanged();
        return this;
      }
      /**
       * <code>string situacao = 1;</code>
       */
      public Builder setSituacaoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        situacao_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:serasa.CpfResponse)
    }

    // @@protoc_insertion_point(class_scope:serasa.CpfResponse)
    private static final com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse();
    }

    public static com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CpfResponse>
        PARSER = new com.google.protobuf.AbstractParser<CpfResponse>() {
      @java.lang.Override
      public CpfResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CpfResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CpfResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CpfResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lucasilva.grpc.integration.grpc.Cpf.CpfResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_serasa_CpfRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_serasa_CpfRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_serasa_CpfResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_serasa_CpfResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tcpf.proto\022\006serasa\"\031\n\nCpfRequest\022\013\n\003cpf" +
      "\030\001 \001(\t\"\037\n\013CpfResponse\022\020\n\010situacao\030\001 \001(\t2" +
      "G\n\nCpfService\0229\n\014consultarCpf\022\022.serasa.C" +
      "pfRequest\032\023.serasa.CpfResponse\"\000B%\n#com." +
      "lucasilva.grpc.integration.grpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_serasa_CpfRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_serasa_CpfRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_serasa_CpfRequest_descriptor,
        new java.lang.String[] { "Cpf", });
    internal_static_serasa_CpfResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_serasa_CpfResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_serasa_CpfResponse_descriptor,
        new java.lang.String[] { "Situacao", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
